### ISSUE TITLE
Logo doesn't link back to homepage

### ISSUE THREAD

**Issue by theLittleBigZ** [the404devs/the404#2]
The404.nl logo in the top left doesn't link back to the homepage when clicked which is a bit jarring for the user as this is expected functionality

**Comment by the404devs** [comment]
It actually does tho, except on the homepage itself

**Comment by theLittleBigZ** [comment]
On Firefox, when the404.nl logo is clicked site does not take me back to the homepage/main page

**Comment by the404devs** [comment]
which page are we talking about here

**Comment by the404devs** [comment]
Issue first appeared in **v2.0.0 (08/27/18)** (I guess, since that was when I introduced the whole multiple-tab thing.)
Issue fixed in **v4.0.2 (06/12/20)** bdd115cf925d2d63473708fb71a9b7a1c2b34f06

Total time to fix: **652 days**
